# Generated by Django 6.0.3 on 2026-04-02 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Traiteur',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nomcomplet', models.CharField(max_length=200)),
                ('specialites', models.TextField()),
                ('description', models.TextField()),
                ('adresse', models.CharField(max_length=150)),
                ('est_actif', models.BooleanField(default=True)),
                ('email', models.EmailField(max_length=254)),
                ('datedecreation', models.DateField()),
                ('telephone', models.CharField()),
                ('image', models.ImageField(upload_to='images/')),
            ],
        ),
    ]
